/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'id' : bigint,
  'userId' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'passwordHash' : string,
}
export type ChangePasswordResult = { 'ok' : null } |
  { 'sessionInvalid' : null } |
  { 'invalidCredentials' : null };
export interface Labour {
  'id' : bigint,
  'workType' : string,
  'dailyWage' : number,
  'name' : string,
  'totalPaid' : number,
  'pendingPayment' : number,
  'siteId' : bigint,
  'phone' : string,
}
export type LoginResult = { 'ok' : string } |
  { 'userNotFound' : null } |
  { 'invalidCredentials' : null };
export type RegisterUserResult = { 'ok' : bigint } |
  { 'emailTaken' : null } |
  { 'userIdTaken' : null };
export type SessionVerificationResult = { 'ok' : AppUser } |
  { 'expired' : null } |
  { 'notFound' : null };
export interface Site {
  'id' : bigint,
  'status' : SiteStatus,
  'clientName' : string,
  'name' : string,
  'totalAmount' : number,
  'notes' : string,
  'location' : string,
  'expectedEndDate' : Time,
  'startDate' : Time,
}
export type SiteStatus = { 'active' : null } |
  { 'completed' : null };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'date' : Time,
  'notes' : string,
  'paymentMode' : string,
  'siteId' : bigint,
  'amount' : number,
}
export type TransactionType = { 'miscExpense' : null } |
  { 'labourPayment' : null } |
  { 'paymentReceived' : null } |
  { 'materialPurchase' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkProgress {
  'id' : bigint,
  'taskName' : string,
  'progressPercent' : number,
  'notes' : string,
  'siteId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<
    [string, string, string],
    ChangePasswordResult
  >,
  'createLabour' : ActorMethod<
    [bigint, string, string, string, number],
    bigint
  >,
  'createSite' : ActorMethod<
    [string, string, string, Time, Time, number, string],
    bigint
  >,
  'createTransaction' : ActorMethod<
    [bigint, Time, TransactionType, number, string, string],
    bigint
  >,
  'createWorkProgress' : ActorMethod<[bigint, string, number, string], bigint>,
  'deleteLabour' : ActorMethod<[bigint], undefined>,
  'deleteSite' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllSites' : ActorMethod<[], Array<Site>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLabour' : ActorMethod<[bigint], Labour>,
  'getLaboursBySiteId' : ActorMethod<[bigint], Array<Labour>>,
  'getSite' : ActorMethod<[bigint], Site>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getTransactionsBySiteId' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserByUserId' : ActorMethod<[string], [] | [AppUser]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkProgress' : ActorMethod<[bigint], WorkProgress>,
  'getWorkProgressBySiteId' : ActorMethod<[bigint], Array<WorkProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], LoginResult>,
  'logoutSession' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<
    [string, string, string, string],
    RegisterUserResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLabour' : ActorMethod<
    [bigint, string, string, string, number, number, number],
    undefined
  >,
  'updateSite' : ActorMethod<
    [bigint, string, string, string, Time, Time, number, string, SiteStatus],
    undefined
  >,
  'updateWorkProgress' : ActorMethod<
    [bigint, string, number, string],
    undefined
  >,
  'verifySession' : ActorMethod<[string], SessionVerificationResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];