/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChangePasswordResult = IDL.Variant({
  'ok' : IDL.Null,
  'sessionInvalid' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const Time = IDL.Int;
export const TransactionType = IDL.Variant({
  'miscExpense' : IDL.Null,
  'labourPayment' : IDL.Null,
  'paymentReceived' : IDL.Null,
  'materialPurchase' : IDL.Null,
});
export const SiteStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const Site = IDL.Record({
  'id' : IDL.Nat,
  'status' : SiteStatus,
  'clientName' : IDL.Text,
  'name' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'location' : IDL.Text,
  'expectedEndDate' : Time,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'workType' : IDL.Text,
  'dailyWage' : IDL.Float64,
  'name' : IDL.Text,
  'totalPaid' : IDL.Float64,
  'pendingPayment' : IDL.Float64,
  'siteId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'date' : Time,
  'notes' : IDL.Text,
  'paymentMode' : IDL.Text,
  'siteId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const AppUser = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const WorkProgress = IDL.Record({
  'id' : IDL.Nat,
  'taskName' : IDL.Text,
  'progressPercent' : IDL.Nat8,
  'notes' : IDL.Text,
  'siteId' : IDL.Nat,
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Text,
  'userNotFound' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const RegisterUserResult = IDL.Variant({
  'ok' : IDL.Nat,
  'emailTaken' : IDL.Null,
  'userIdTaken' : IDL.Null,
});
export const SessionVerificationResult = IDL.Variant({
  'ok' : AppUser,
  'expired' : IDL.Null,
  'notFound' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ChangePasswordResult],
      [],
    ),
  'createLabour' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createSite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, Time, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Nat, Time, TransactionType, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createWorkProgress' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat8, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteLabour' : IDL.Func([IDL.Nat], [], []),
  'deleteSite' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLabour' : IDL.Func([IDL.Nat], [Labour], ['query']),
  'getLaboursBySiteId' : IDL.Func([IDL.Nat], [IDL.Vec(Labour)], ['query']),
  'getSite' : IDL.Func([IDL.Nat], [Site], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactionsBySiteId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserByUserId' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkProgress' : IDL.Func([IDL.Nat], [WorkProgress], ['query']),
  'getWorkProgressBySiteId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkProgress)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logoutSession' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RegisterUserResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLabour' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateSite' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Float64,
        IDL.Text,
        SiteStatus,
      ],
      [],
      [],
    ),
  'updateWorkProgress' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat8, IDL.Text],
      [],
      [],
    ),
  'verifySession' : IDL.Func([IDL.Text], [SessionVerificationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChangePasswordResult = IDL.Variant({
    'ok' : IDL.Null,
    'sessionInvalid' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const Time = IDL.Int;
  const TransactionType = IDL.Variant({
    'miscExpense' : IDL.Null,
    'labourPayment' : IDL.Null,
    'paymentReceived' : IDL.Null,
    'materialPurchase' : IDL.Null,
  });
  const SiteStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Site = IDL.Record({
    'id' : IDL.Nat,
    'status' : SiteStatus,
    'clientName' : IDL.Text,
    'name' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'location' : IDL.Text,
    'expectedEndDate' : Time,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'workType' : IDL.Text,
    'dailyWage' : IDL.Float64,
    'name' : IDL.Text,
    'totalPaid' : IDL.Float64,
    'pendingPayment' : IDL.Float64,
    'siteId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'date' : Time,
    'notes' : IDL.Text,
    'paymentMode' : IDL.Text,
    'siteId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const AppUser = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const WorkProgress = IDL.Record({
    'id' : IDL.Nat,
    'taskName' : IDL.Text,
    'progressPercent' : IDL.Nat8,
    'notes' : IDL.Text,
    'siteId' : IDL.Nat,
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Text,
    'userNotFound' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const RegisterUserResult = IDL.Variant({
    'ok' : IDL.Nat,
    'emailTaken' : IDL.Null,
    'userIdTaken' : IDL.Null,
  });
  const SessionVerificationResult = IDL.Variant({
    'ok' : AppUser,
    'expired' : IDL.Null,
    'notFound' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ChangePasswordResult],
        [],
      ),
    'createLabour' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createSite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, Time, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Nat, Time, TransactionType, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createWorkProgress' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat8, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteLabour' : IDL.Func([IDL.Nat], [], []),
    'deleteSite' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLabour' : IDL.Func([IDL.Nat], [Labour], ['query']),
    'getLaboursBySiteId' : IDL.Func([IDL.Nat], [IDL.Vec(Labour)], ['query']),
    'getSite' : IDL.Func([IDL.Nat], [Site], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactionsBySiteId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserByUserId' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkProgress' : IDL.Func([IDL.Nat], [WorkProgress], ['query']),
    'getWorkProgressBySiteId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkProgress)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logoutSession' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [RegisterUserResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLabour' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateSite' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Float64,
          IDL.Text,
          SiteStatus,
        ],
        [],
        [],
      ),
    'updateWorkProgress' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat8, IDL.Text],
        [],
        [],
      ),
    'verifySession' : IDL.Func([IDL.Text], [SessionVerificationResult], []),
  });
};

export const init = ({ IDL }) => { return []; };