/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Labour {
    id: bigint;
    workType: string;
    dailyWage: number;
    name: string;
    totalPaid: number;
    pendingPayment: number;
    siteId: bigint;
    phone: string;
}
export type Time = bigint;
export type RegisterUserResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "emailTaken";
    emailTaken: null;
} | {
    __kind__: "userIdTaken";
    userIdTaken: null;
};
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    date: Time;
    notes: string;
    paymentMode: string;
    siteId: bigint;
    amount: number;
}
export interface WorkProgress {
    id: bigint;
    taskName: string;
    progressPercent: number;
    notes: string;
    siteId: bigint;
}
export interface AppUser {
    id: bigint;
    userId: string;
    name: string;
    createdAt: Time;
    email: string;
    passwordHash: string;
}
export interface Site {
    id: bigint;
    status: SiteStatus;
    clientName: string;
    name: string;
    totalAmount: number;
    notes: string;
    location: string;
    expectedEndDate: Time;
    startDate: Time;
}
export type SessionVerificationResult = {
    __kind__: "ok";
    ok: AppUser;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export type LoginResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
};
export interface UserProfile {
    name: string;
}
export enum ChangePasswordResult {
    ok = "ok",
    sessionInvalid = "sessionInvalid",
    invalidCredentials = "invalidCredentials"
}
export enum SiteStatus {
    active = "active",
    completed = "completed"
}
export enum TransactionType {
    miscExpense = "miscExpense",
    labourPayment = "labourPayment",
    paymentReceived = "paymentReceived",
    materialPurchase = "materialPurchase"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changePassword(token: string, oldPassword: string, newPassword: string): Promise<ChangePasswordResult>;
    createLabour(siteId: bigint, name: string, phone: string, workType: string, dailyWage: number): Promise<bigint>;
    createSite(name: string, clientName: string, location: string, startDate: Time, expectedEndDate: Time, totalAmount: number, notes: string): Promise<bigint>;
    createTransaction(siteId: bigint, date: Time, transactionType: TransactionType, amount: number, paymentMode: string, notes: string): Promise<bigint>;
    createWorkProgress(siteId: bigint, taskName: string, progressPercent: number, notes: string): Promise<bigint>;
    deleteLabour(id: bigint): Promise<void>;
    deleteSite(id: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    getAllSites(): Promise<Array<Site>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLabour(id: bigint): Promise<Labour>;
    getLaboursBySiteId(siteId: bigint): Promise<Array<Labour>>;
    getSite(id: bigint): Promise<Site>;
    getTransaction(id: bigint): Promise<Transaction>;
    getTransactionsBySiteId(siteId: bigint): Promise<Array<Transaction>>;
    getUserByUserId(userId: string): Promise<AppUser | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkProgress(id: bigint): Promise<WorkProgress>;
    getWorkProgressBySiteId(siteId: bigint): Promise<Array<WorkProgress>>;
    isCallerAdmin(): Promise<boolean>;
    loginUser(userId: string, password: string): Promise<LoginResult>;
    logoutSession(token: string): Promise<void>;
    registerUser(userId: string, name: string, email: string, password: string): Promise<RegisterUserResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateLabour(id: bigint, name: string, phone: string, workType: string, dailyWage: number, totalPaid: number, pendingPayment: number): Promise<void>;
    updateSite(id: bigint, name: string, clientName: string, location: string, startDate: Time, expectedEndDate: Time, totalAmount: number, notes: string, status: SiteStatus): Promise<void>;
    updateWorkProgress(id: bigint, taskName: string, progressPercent: number, notes: string): Promise<void>;
    verifySession(token: string): Promise<SessionVerificationResult>;
}
import type { AppUser as _AppUser, ChangePasswordResult as _ChangePasswordResult, LoginResult as _LoginResult, RegisterUserResult as _RegisterUserResult, SessionVerificationResult as _SessionVerificationResult, Site as _Site, SiteStatus as _SiteStatus, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changePassword(arg0: string, arg1: string, arg2: string): Promise<ChangePasswordResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1, arg2);
                return from_candid_ChangePasswordResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1, arg2);
            return from_candid_ChangePasswordResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLabour(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabour(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabour(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createSite(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: Time, arg5: number, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSite(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSite(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createTransaction(arg0: bigint, arg1: Time, arg2: TransactionType, arg3: number, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1, to_candid_TransactionType_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1, to_candid_TransactionType_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async createWorkProgress(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkProgress(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkProgress(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteLabour(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabour(arg0);
            return result;
        }
    }
    async deleteSite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSite(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAllSites(): Promise<Array<Site>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSites();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSites();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLabour(arg0: bigint): Promise<Labour> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabour(arg0);
            return result;
        }
    }
    async getLaboursBySiteId(arg0: bigint): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaboursBySiteId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaboursBySiteId(arg0);
            return result;
        }
    }
    async getSite(arg0: bigint): Promise<Site> {
        if (this.processError) {
            try {
                const result = await this.actor.getSite(arg0);
                return from_candid_Site_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSite(arg0);
            return from_candid_Site_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_Transaction_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_Transaction_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsBySiteId(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsBySiteId(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsBySiteId(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByUserId(arg0: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUserId(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUserId(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkProgress(arg0: bigint): Promise<WorkProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkProgress(arg0);
            return result;
        }
    }
    async getWorkProgressBySiteId(arg0: bigint): Promise<Array<WorkProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkProgressBySiteId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkProgressBySiteId(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_LoginResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_LoginResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutSession(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<RegisterUserResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return from_candid_RegisterUserResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return from_candid_RegisterUserResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateLabour(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSite(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time, arg6: number, arg7: string, arg8: SiteStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_SiteStatus_n25(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_SiteStatus_n25(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateWorkProgress(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkProgress(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkProgress(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifySession(arg0: string): Promise<SessionVerificationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySession(arg0);
                return from_candid_SessionVerificationResult_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySession(arg0);
            return from_candid_SessionVerificationResult_n27(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChangePasswordResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChangePasswordResult): ChangePasswordResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterUserResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterUserResult): RegisterUserResult {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SessionVerificationResult_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionVerificationResult): SessionVerificationResult {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SiteStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteStatus): SiteStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Site_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Site): Site {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUser]): AppUser | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    date: _Time;
    notes: string;
    paymentMode: string;
    siteId: bigint;
    amount: number;
}): {
    id: bigint;
    transactionType: TransactionType;
    date: Time;
    notes: string;
    paymentMode: string;
    siteId: bigint;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n17(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        notes: value.notes,
        paymentMode: value.paymentMode,
        siteId: value.siteId,
        amount: value.amount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SiteStatus;
    clientName: string;
    name: string;
    totalAmount: number;
    notes: string;
    location: string;
    expectedEndDate: _Time;
    startDate: _Time;
}): {
    id: bigint;
    status: SiteStatus;
    clientName: string;
    name: string;
    totalAmount: number;
    notes: string;
    location: string;
    expectedEndDate: Time;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_SiteStatus_n10(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        name: value.name,
        totalAmount: value.totalAmount,
        notes: value.notes,
        location: value.location,
        expectedEndDate: value.expectedEndDate,
        startDate: value.startDate
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): SiteStatus {
    return "active" in value ? SiteStatus.active : "completed" in value ? SiteStatus.completed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    miscExpense: null;
} | {
    labourPayment: null;
} | {
    paymentReceived: null;
} | {
    materialPurchase: null;
}): TransactionType {
    return "miscExpense" in value ? TransactionType.miscExpense : "labourPayment" in value ? TransactionType.labourPayment : "paymentReceived" in value ? TransactionType.paymentReceived : "materialPurchase" in value ? TransactionType.materialPurchase : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    userNotFound: null;
} | {
    invalidCredentials: null;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "userNotFound" in value ? {
        __kind__: "userNotFound",
        userNotFound: value.userNotFound
    } : "invalidCredentials" in value ? {
        __kind__: "invalidCredentials",
        invalidCredentials: value.invalidCredentials
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    emailTaken: null;
} | {
    userIdTaken: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "emailTaken";
    emailTaken: null;
} | {
    __kind__: "userIdTaken";
    userIdTaken: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "emailTaken" in value ? {
        __kind__: "emailTaken",
        emailTaken: value.emailTaken
    } : "userIdTaken" in value ? {
        __kind__: "userIdTaken",
        userIdTaken: value.userIdTaken
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AppUser;
} | {
    expired: null;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: AppUser;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    sessionInvalid: null;
} | {
    invalidCredentials: null;
}): ChangePasswordResult {
    return "ok" in value ? ChangePasswordResult.ok : "sessionInvalid" in value ? ChangePasswordResult.sessionInvalid : "invalidCredentials" in value ? ChangePasswordResult.invalidCredentials : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Site>): Array<Site> {
    return value.map((x)=>from_candid_Site_n8(_uploadFile, _downloadFile, x));
}
function to_candid_SiteStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteStatus): _SiteStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteStatus): {
    active: null;
} | {
    completed: null;
} {
    return value == SiteStatus.active ? {
        active: null
    } : value == SiteStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    miscExpense: null;
} | {
    labourPayment: null;
} | {
    paymentReceived: null;
} | {
    materialPurchase: null;
} {
    return value == TransactionType.miscExpense ? {
        miscExpense: null
    } : value == TransactionType.labourPayment ? {
        labourPayment: null
    } : value == TransactionType.paymentReceived ? {
        paymentReceived: null
    } : value == TransactionType.materialPurchase ? {
        materialPurchase: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
